#!/usr/bin/env bash
# P0-8: ops-center systemd setup script
# Run as root on deployment machine
set -euo pipefail

SERVICE_NAME="ops-center"
ENV_FILE="/etc/${SERVICE_NAME}/env"
INSTALL_DIR="/opt/${SERVICE_NAME}"
DATA_DIR="/data/${SERVICE_NAME}"
CONFIG_OUTPUT="/data/configs"

echo "[setup] Creating dedicated user..."
id -u ${SERVICE_NAME} &>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin ${SERVICE_NAME}

echo "[setup] Creating directories..."
mkdir -p "${INSTALL_DIR}/backend" "${DATA_DIR}" "${CONFIG_OUTPUT}" "/etc/${SERVICE_NAME}"
chown -R ${SERVICE_NAME}:${SERVICE_NAME} "${INSTALL_DIR}" "${DATA_DIR}" "${CONFIG_OUTPUT}"

echo "[setup] Generating secrets (skip if env file exists)..."
if [[ ! -f "${ENV_FILE}" ]]; then
  ENC_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
  JWT_SECRET=$(openssl rand -hex 32)
  SECRET_KEY=$(openssl rand -hex 32)
  cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-service.sh at $(date -Iseconds)
OPS_ENCRYPTION_KEY=${ENC_KEY}
OPS_JWT_SECRET=${JWT_SECRET}
OPS_SECRET_KEY=${SECRET_KEY}
OPS_CORS_ORIGINS=https://your-domain.com
OPS_ADMIN_PASSWORD=CHANGE_ME_BEFORE_START
EOF
  chown ${SERVICE_NAME}:${SERVICE_NAME} "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "[setup] Written ${ENV_FILE} — EDIT OPS_CORS_ORIGINS and OPS_ADMIN_PASSWORD before starting!"
else
  echo "[setup] ${ENV_FILE} exists, skipping key generation"
fi

echo "[setup] Installing systemd unit..."
cp "$(dirname "$0")/ops-center.service" /etc/systemd/system/${SERVICE_NAME}.service
systemctl daemon-reload
systemctl enable ${SERVICE_NAME}

echo ""
echo "[setup] DONE. Next steps:"
echo "  1. Edit ${ENV_FILE} (CORS origins, admin password)"
echo "  2. Deploy latest code to ${INSTALL_DIR}/backend"
echo "  3. systemctl start ${SERVICE_NAME}"
echo "  4. journalctl -u ${SERVICE_NAME} -f  (verify startup passes P0 checks)"
